### ISSUE TITLE
Wrong case in property names

### ISSUE THREAD

**Issue by pellenilsson** [wgoossens/sopc2dts#1]
Property names currently use capital letters for the ALTR part (e.g. `"ALTR,exception-addr"`), but after the Nios was merged into mainline the kernel only recognizes properties written in small caps. Among other things, this causes an early kernel panic since the kernel doesn't find the `"altr,has-initda"` property of the cpu node, so it's no longer possible to even boot with device trees created by this tool.

Simplest solution would be to switch to small caps, but that would probably break compatibility with old kernels (that look for big caps), so maybe we should add a command line option for this?

**Comment by pellenilsson** [comment]
Some elaboration, this is the current kernel macros that compare strings versus the device tree (in `include/linux/of.h`):

```
#define of_compat_cmp(s1, s2, l)    strcasecmp((s1), (s2))
#define of_prop_cmp(s1, s2)     strcmp((s1), (s2))
#define of_node_cmp(s1, s2)     strcasecmp((s1), (s2))
```

So only property names are case sensitive, not compatibility strings.

**Comment by wgoossens** [comment]
Actually it's even worse....

When using a sopcinfo file from Quartus 14.1 you'll always get _lowercase_ altr. Altera followed the upstream changing of ALTR to altr in Quartus 14.1 but there is no relation between Quartus and Linux kernel versions.
There are now people using a new kernel and "old" Quartus that can't boot AND people with new Quartus and old kernel fail to boot.
To muddy this even more, the lowercase stuff is also backported to some of the ltsi branches at rocketboards so there are 3.10 versions that use ALTR and 3.10 versions that require altr :(
I'm doing everything in my might to prevent creating kernel/quartus version specific quirks because a devicetree is a description of _hardware_ not of software drivers using it.... 

Maybe a commandline option forcing ALTR or altr would be a (quite ugly but for the time being usable) solution?

Walter

**Comment by wgoossens** [comment]
I've added --force-altr and --force-ALTR parameters. Guess what they do ;)

**Comment by pellenilsson** [comment]
Thanks!

Actually, I get capital ALTR even from Quartus 14.1.0. Maybe 14.1 update 1 is required? But with these options it doesn't matter.
