### ISSUE TITLE
Feature request - Accept DTB/DTS as input for DTS/DTB transform 

### ISSUE THREAD

**Issue by integretek-hsandlar** [wgoossens/sopc2dts#3]
This is not an issue with the existing implementation -- just a feature request.

It would be useful if this tool supported DTB/DTS input as an option. I would like to use this tool as a generalized DTB/DTS customization mechanism in non-Altera systems. I may look into forking this repository and implementing this myself.

**Comment by wgoossens** [comment]
Hi,

I've been wondering about this myself, I might even have some code laying around for this, I'll have to dig a bit since it's been a while since I've really worked on this. The system is designed to be somewhat input agnostic, but since the only finalized input module is for Altera systems, it might have become somewhat Altera specific. 

What features are you missing with the existing dtc and overlay systems? I seem to remember not bothering with dts input since the dtc is getting really flexible now a days (although I personally feel this is not always beneficial for the readability of the device-trees....).

I've looked into adding support for other SoC types but never have needed it enough to complete it.

Walter

**Comment by integretek-hsandlar** [comment]
Hi,

My apologies for the long delay in responding on this. I had not used device tree overlays in the past and wanted to make sure to try working them into my flow before pushing this issue any further. I'm working on a Xilinx SoC and unfortunately they don't offer any easy mechanism to modify device trees. The FAE's say that the standard approach by most designers is to hand-edit the Vivado-generated DTS which is quite painful when coming from an Altera (sopc2dts) flow. In particular I wanted to make sure that I didn't have to maintain a hand-edited DTS in which the base DTS generated by Vivado may vary greatly depending on the described fabric design.

Anyway, after reviewing dtc and providing a yocto recipe for 1.4.5 (which includes fdtoverlay support), I was able to write a recipe to transform my device tree with overlays. In general, I think the sopc2dts input format (XML description) is much more intuitive than dtc's overlay format but at the moment I don't have any need to develop dts/dtb input for sopc2dts as I've been able to get my system working with overlays.

Thanks for the consideration on this issue though.

Holden
