### ISSUE TITLE
No support for interface and components

### ISSUE THREAD

**Issue by kubux1** [wgoossens/sopc2dts#8]
When I generate a dts from sopcinfo file I get a following warnings:
Unsupported interface kind: hssi_serial_clock_source
Component pcie_a10_hip of class altera_pcie_a10_hip is unknown
Component xcvr_fpll_a10 of class altera_xcvr_fpll_a10 is unknown
Component pcie_a10_hip of class altera_pcie_a10_hip is unknown
Component xcvr_fpll_a10 of class altera_xcvr_fpll_a10 is unknown

Is it affecting my final dts content? 
If yes, is it possible to add support for this interface and components?

**Comment by wgoossens** [comment]
Hi kubux,

you probably _do_ want support for the pcie_a10_hip component (PCIe HardIP on arraia10 would be my guess) but I'm not sure if Intel has support for that. It might not be trivial to add, depending on what's needed. 
Do you have/use a driver for the PCIe core?
I don't have an arria10 so I can't test I'm afraid.
Have you asked your FAE about this?
Back in the Altera days I had my ways in the company but a lot has changed since they became Intel, I haven't heard from them since the name change....

Walter

**Comment by wgoossens** [comment]
Closing due to lack of response
